---
name: Parse-Fedora-Packages
version: 0.01
author:
  - Gabor Szabo
abstract: Parse Fedora package information
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  XML::Simple: 0
build_requires:
  Test::More: 0.47
provides:
  Parse::Fedora::Packages:
    file: lib/Parse/Fedora/Packages.pm
    version: 0.01
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
